vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.mouse = "a"
vim.opt.clipboard = "unnamedplus"
vim.opt.tabstop = 4       -- Number of spaces a <Tab> character represents
vim.opt.shiftwidth = 4    -- Number of spaces to use for each indentation level
vim.opt.expandtab = true  -- Convert tabs to spaces
vim.opt.termguicolors = true
vim.opt.background = "dark"
vim.opt.autoindent = true
vim.opt.smartindent = true
